console.log("Hello")
let mySprite = sprites.create(, SpriteKind.Player)
let mySprite2 = sprites.create(, SpriteKind.Player)
game.setDialogTextColor(15)
let statusbar = statusbars.create(20, 4, StatusBarKind.Health)
let New = statusbars.create(20, 4, StatusBarKind.Health)
statusbar.attachToSprite(mySprite)
New.attachToSprite(mySprite2)
let Again = sprites.create(, SpriteKind.Player)
